### ISSUE TITLE
README example throws error

### ISSUE THREAD

**Issue by rafaellehmkuhl** [pallets/flask-sqlalchemy#820]
If I try to run the example from the repository README, it throws this error:

> python3 app.py/home/username/.local/lib/python3.8/site-packages/flask_sqlalchemy/__init__.py:834: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
>   warnings.warn(FSADeprecationWarning(
> Traceback (most recent call last):
>   File "/home/username/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1283, in _execute_context
>     self.dialect.do_execute(
>   File "/home/username/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 590, in do_execute
>     cursor.execute(statement, parameters)
> sqlite3.OperationalError: no such table: user
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "app.py", line 16, in <module>
>     db.session.commit()
>   File "/home/username/.local/lib/python3.8/site-packages/sqlalchemy/orm/scoping.py", line 163, in do
>     return getattr(self.registry(), name)(*args, **kwargs)
>   File "/home/username/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1042, in commit
>     self.transaction.commit()
>   File "/home/username/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 504, in commit
>     self._prepare_impl()
>   File "/home/username/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 483, in _prepare_impl
>     self.session.flush()
>   File "/home/username/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2523, in flush
>     self._flush(objects)
>   File "/home/username/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2664, in _flush
>     transaction.rollback(_capture_exception=True)
>   File "/home/username/.local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
>     compat.raise_(
>   File "/home/username/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
>     raise exception
>   File "/home/username/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2624, in _flush
>     flush_context.execute()
>   File "/home/username/.local/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
>     rec.execute(self)
>   File "/home/username/.local/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py", line 586, in execute
>     persistence.save_obj(
>   File "/home/username/.local/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 239, in save_obj
>     _emit_insert_statements(
>   File "/home/username/.local/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 1135, in _emit_insert_statements
>     result = cached_connections[connection].execute(
>   File "/home/username/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1020, in execute
>     return meth(self, multiparams, params)
>   File "/home/username/.local/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
>     return connection._execute_clauseelement(self, multiparams, params)
>   File "/home/username/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1133, in _execute_clauseelement
>     ret = self._execute_context(
>   File "/home/username/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1323, in _execute_context
>     self._handle_dbapi_exception(
>   File "/home/username/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1517, in _handle_dbapi_exception
>     util.raise_(
>   File "/home/username/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
>     raise exception
>   File "/home/username/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1283, in _execute_context
>     self.dialect.do_execute(
>   File "/home/username/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 590, in do_execute
>     cursor.execute(statement, parameters)
> sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: user
> [SQL: INSERT INTO user (username, email) VALUES (?, ?)]
> [parameters: ('Flask', 'example@example.com')]
> (Background on this error at: http://sqlalche.me/e/e3q8)

Is it expected?

**Comment by rafaellehmkuhl** [comment]
Wouldn't it be good to explicit this in the README? I think it is very misleading to new users.
