### ISSUE TITLE
How to handle database restart

### ISSUE THREAD

**Issue by tyctor** [pallets/flask-sqlalchemy#893]
I am creating flask app with flask_sqlalchemy orm, during develop i found circumstances in which app fails and i am not sure what is simple way how to handle it.
Imagine running app, which is responding to user browser (e.g. Flask-Admin) `and this app already did some responses.`
Now on backend side i need to restart DB server (postgres), restart is done and DB server is already up.
Now when i go back to browser and refresh page, and i will get `sqlalchemy.exc.OperationalError`

```
sqlalchemy.exc.OperationalError: (psycopg2.errors.AdminShutdown) terminating connection 
due to administrator command server closed the connection unexpectedly
This probably means the server terminated abnormally
before or while processing the request.
```

but this is not true, because DB is already up, and i need restart flask app to get it working.

when i start app, and i restart DB `before any request` (so not request was handled by app)
this error not occurs and app is working well.

i think that some session or db connection is cached with request, and is not invalidated if `OperationalError` occurs

what is best way to handle this?
i already tryied, but without success:
 - to create_engine with `pool_pre_ping=True`
 - to create_engine with `poolclass=NullPool` to get new connection with each request
 - invalidating `Session` after request

what is working for me, but i think is ugly solution, is to use flask errohandler
```    
    @app.errorhandler(OperationalError)
    def handle_operational_error(error):
        db.session.rollback()
        db.session.close_all()
        count = int(request.args.get('_err', -1))
        if count > 0:
            raise error
        count += 1
        return redirect(request.path + f'?_err={count}')
```

such error never happened to me with django orm.

is there some standart way how to handle this?
thanks for any hints

guy from sqlalchemy point me to flask community:

> the idea is that every Flask request is responsible for closing its own session. If your requests are not doing that, they are leaving connections / transactions dangling between requests, and that is a bug either in your application or within flask. "close_all_sessions()" is a bad antipattern because it indicates your application is not keeping track of where it is making use of database connections and is not cleaning up after itself when a request ends. you will down the road have problems much worse than disconnects, with PG you'll see a lot of deadlocks too. There's definitely a lot of help to be had within the Flask community about this issue.

so probably best place to ask is here, as it is Flask-SQLAlchemy repo 
https://github.com/sqlalchemy/sqlalchemy/issues/5776
below is traceback what i getting
```
Traceback (most recent call last):
  File "/home/flaskapp/eggs/SQLAlchemy-1.3.17-py3.6-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1284, in _execute_context
    cursor, statement, parameters, context
  File "/home/flaskapp/eggs/SQLAlchemy-1.3.17-py3.6-linux-x86_64.egg/sqlalchemy/engine/default.py", line 590, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.AdminShutdown: terminating connection due to administrator command
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/flaskapp/eggs/Flask-1.1.2-py3.6.egg/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/flaskapp/eggs/Flask-1.1.2-py3.6.egg/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/home/flaskapp/eggs/Flask_RESTful-0.3.8-py3.6.egg/flask_restful/__init__.py", line 272, in error_router
    return original_handler(e)
  File "/home/flaskapp/eggs/Flask-1.1.2-py3.6.egg/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/flaskapp/eggs/Flask-1.1.2-py3.6.egg/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/flaskapp/eggs/Flask-1.1.2-py3.6.egg/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/flaskapp/eggs/Flask-1.1.2-py3.6.egg/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/flaskapp/eggs/Flask_RESTful-0.3.8-py3.6.egg/flask_restful/__init__.py", line 272, in error_router
    return original_handler(e)
  File "/home/flaskapp/eggs/Flask-1.1.2-py3.6.egg/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/flaskapp/eggs/Flask-1.1.2-py3.6.egg/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/flaskapp/eggs/Flask-1.1.2-py3.6.egg/flask/app.py", line 1948, in full_dispatch_request
    rv = self.preprocess_request()
  File "/home/flaskapp/eggs/Flask-1.1.2-py3.6.egg/flask/app.py", line 2242, in preprocess_request
    rv = func()
  File "/home/flaskapp/eggs/Flask_Principal-0.4.0-py3.6.egg/flask_principal.py", line 477, in _on_before_request
    identity = loader()
  File "/home/flaskapp/eggs/Flask_Security_Too-3.4.3-py3.6.egg/flask_security/core.py", line 515, in _identity_loader
    if not isinstance(current_user._get_current_object(), AnonymousUserMixin):
  File "/home/flaskapp/eggs/Werkzeug-1.0.1-py3.6.egg/werkzeug/local.py", line 306, in _get_current_object
    return self.__local()
  File "/home/flaskapp/eggs/Flask_Login-0.5.0-py3.6.egg/flask_login/utils.py", line 26, in <lambda>
    current_user = LocalProxy(lambda: _get_user())
  File "/home/flaskapp/eggs/Flask_Login-0.5.0-py3.6.egg/flask_login/utils.py", line 346, in _get_user
    current_app.login_manager._load_user()
  File "/home/flaskapp/eggs/Flask_Login-0.5.0-py3.6.egg/flask_login/login_manager.py", line 318, in _load_user
    user = self._user_callback(user_id)
  File "/home/flaskapp/eggs/Flask_Security_Too-3.4.3-py3.6.egg/flask_security/core.py", line 455, in _user_loader
    user = _security.datastore.find_user(**selector)
  File "/home/flaskapp/eggs/Flask_Security_Too-3.4.3-py3.6.egg/flask_security/datastore.py", line 512, in find_user
    return query.filter_by(**kwargs).first()
  File "/home/flaskapp/eggs/SQLAlchemy-1.3.17-py3.6-linux-x86_64.egg/sqlalchemy/orm/query.py", line 3375, in first
    ret = list(self[0:1])
  File "/home/flaskapp/eggs/SQLAlchemy-1.3.17-py3.6-linux-x86_64.egg/sqlalchemy/orm/query.py", line 3149, in __getitem__
    return list(res)
  File "/home/flaskapp/eggs/SQLAlchemy-1.3.17-py3.6-linux-x86_64.egg/sqlalchemy/orm/query.py", line 3481, in __iter__
    return self._execute_and_instances(context)
  File "/home/flaskapp/eggs/SQLAlchemy-1.3.17-py3.6-linux-x86_64.egg/sqlalchemy/orm/query.py", line 3506, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/home/flaskapp/eggs/SQLAlchemy-1.3.17-py3.6-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1020, in execute
    return meth(self, multiparams, params)
  File "/home/flaskapp/eggs/SQLAlchemy-1.3.17-py3.6-linux-x86_64.egg/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/flaskapp/eggs/SQLAlchemy-1.3.17-py3.6-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1139, in _execute_clauseelement
    distilled_params,
  File "/home/flaskapp/eggs/SQLAlchemy-1.3.17-py3.6-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1324, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/flaskapp/eggs/SQLAlchemy-1.3.17-py3.6-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1518, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/flaskapp/eggs/SQLAlchemy-1.3.17-py3.6-linux-x86_64.egg/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/home/flaskapp/eggs/SQLAlchemy-1.3.17-py3.6-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1284, in _execute_context
    cursor, statement, parameters, context
  File "/home/flaskapp/eggs/SQLAlchemy-1.3.17-py3.6-linux-x86_64.egg/sqlalchemy/engine/default.py", line 590, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (psycopg2.errors.AdminShutdown) terminating connection due to administrator command
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.

[SQL: SELECT anon_1."User_id" AS "anon_1_User_id", anon_1."User_firstName" AS "anon_1_User_firstName", anon_1."User_lastName" AS "anon_1_User_lastName", anon_1."User_email" AS "anon_1_User_email", anon_1."User_password" AS "anon_1_User_password", anon_1."User__scopes" AS "anon_1_User__scopes", anon_1."User_last_login_at" AS "anon_1_User_last_login_at", anon_1."User_current_login_at" AS "anon_1_User_current_login_at", anon_1."User_last_login_ip" AS "anon_1_User_last_login_ip", anon_1."User_current_login_ip" AS "anon_1_User_current_login_ip", anon_1."User_login_count" AS "anon_1_User_login_count", anon_1."User_active" AS "anon_1_User_active", anon_1."User_fs_uniquifier" AS "anon_1_User_fs_uniquifier", anon_1."User_confirmed_at" AS "anon_1_User_confirmed_at", anon_1."User_is_superuser" AS "anon_1_User_is_superuser", anon_1."User_is_staff" AS "anon_1_User_is_staff", anon_1."User_is_idissuer" AS "anon_1_User_is_idissuer", anon_1."User_iiid" AS "anon_1_User_iiid", anon_1."User_is_eo" AS "anon_1_User_is_eo", anon_1."User_eoid" AS "anon_1_User_eoid", role_1.id AS role_1_id, role_1.name AS role_1_name, role_1.description AS role_1_description 
FROM (SELECT "User".id AS "User_id", "User"."firstName" AS "User_firstName", "User"."lastName" AS "User_lastName", "User".email AS "User_email", "User".password AS "User_password", "User"._scopes AS "User__scopes", "User".last_login_at AS "User_last_login_at", "User".current_login_at AS "User_current_login_at", "User".last_login_ip AS "User_last_login_ip", "User".current_login_ip AS "User_current_login_ip", "User".login_count AS "User_login_count", "User".active AS "User_active", "User".fs_uniquifier AS "User_fs_uniquifier", "User".confirmed_at AS "User_confirmed_at", "User".is_superuser AS "User_is_superuser", "User".is_staff AS "User_is_staff", "User".is_idissuer AS "User_is_idissuer", "User".iiid AS "User_iiid", "User".is_eo AS "User_is_eo", "User".eoid AS "User_eoid" 
FROM "User" 
WHERE "User".fs_uniquifier = %(fs_uniquifier_1)s 
 LIMIT %(param_1)s) AS anon_1 LEFT OUTER JOIN (roles_users AS roles_users_1 JOIN role AS role_1 ON role_1.id = roles_users_1.role_id) ON anon_1."User_id" = roles_users_1.user_id]
[parameters: {'fs_uniquifier_1': '9dd1167c88f84bd594a690cb6e1b237d', 'param_1': 1}]
(Background on this error at: http://sqlalche.me/e/e3q8)
```

**Comment by davidism** [comment]
Sessions are already removed when the request is torn down.

https://github.com/pallets/flask-sqlalchemy/blob/868ba17916458d7f8eaeee292055c56432c80d91/src/flask_sqlalchemy/__init__.py#L852

**Comment by davidism** [comment]
I can't reproduce this with the following example. Visiting the page, restarting Postgres, and visiting again works correctly with pre-ping.

```python
from flask import Flask
from flask_sqlalchemy import SQLAlchemy

app = Flask(__name__)
app.config["SQLALCHEMY_DATABASE_URI"] = "postgresql:///fsqla_test"
app.config["SQLALCHEMY_ENGINE_OPTIONS"] = {
    "echo": True,
    "echo_pool": "debug",
    "pool_pre_ping": True,
}
db = SQLAlchemy()
db.init_app(app)


@app.route("/")
def index():
    out = db.session.execute("select 'hello'").fetchone()[0]
    db.session.commit()
    return out
```

**Comment by tyctor** [comment]
ok thanks for reply
i will try to prepare reproducible example (or i will find where is mistake in my code)

**Comment by tyctor** [comment]
i tryied to put some print into code
what i found is, that line 860
https://github.com/pallets/flask-sqlalchemy/blob/e5fcf6242077d5a50bab21b5cb186830e6a526c6/flask_sqlalchemy/__init__.py#L860
is session creating new session and removing that new instance instead of removing existing session
have you any idea why this happens?
