### ISSUE TITLE
Release 2.5.0 is not py27 compatible?

### ISSUE THREAD

**Issue by POD666** [pallets/flask-sqlalchemy#936]
I use Airflow 1.10.9 that is expected to support py27 but looks like your recent release breaks it.
Just let me know if it's intended. - I will then open an issue for Airflow to pin `Flask-SQLAlchemy<2.5` to keep compatibility.
```
Traceback (most recent call last):
  ...
  from airflow.bin.cli import CLIFactory
  File "...tox/dbnd-aws/py27/lib/python2.7/site-packages/airflow/bin/cli.py", line 71, in <module>
    from airflow.www_rbac.app import cached_app as cached_app_rbac
  File "...tox/dbnd-aws/py27/lib/python2.7/site-packages/airflow/www_rbac/app.py", line 27, in <module>
    from flask_appbuilder import AppBuilder, SQLA
  File "...tox/dbnd-aws/py27/lib/python2.7/site-packages/flask_appbuilder/__init__.py", line 4, in <module>
    from .models.sqla import Model, Base, SQLA
  File "...tox/dbnd-aws/py27/lib/python2.7/site-packages/flask_appbuilder/models/sqla/__init__.py", line 5, in <module>
    from flask_sqlalchemy import SQLAlchemy, DefaultMeta, _QueryProperty
  File "...tox/dbnd-aws/py27/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py", line 39, in <module>
    from threading import get_ident as _ident_func
ImportError: cannot import name get_ident
```

Environment:

- Python version: 2.7
- Flask-SQLAlchemy version: 2.5.0

**Comment by davidism** [comment]
It's not intended, but just heads up that 2.7 has been unsupported for over a year now, and will not be supported at all in the next feature release.

**Comment by davidism** [comment]
2.5.1 released
