### ISSUE TITLE
`NoneType` object has no attribute `setdefault`

### ISSUE THREAD

**Issue by cnicodeme** [pallets/flask-sqlalchemy#947]
I'm aware a previous ticket has been closed about this (#928), but it seems that the issue is still present with the latest versions of SQLAlchemy + Flask-SQLAlchemy

In order to make it work, I had to revert both libs to the following version:

```
SQLAlchemy==1.3.24
Flask-SQLAlchemy==2.4.4
```

The issue for me was located at `apply_driver_hacks()` on __init__.py at line 937 (on SA I believe)

```
if sa_url.drivername != 'mysql+gaerdbms':
        options.setdefault('pool_size', 10)  # <- this is the faulty one
```

I'm posting here for both your information and to help out others if they need it: reverting to the above-mentioned versions fixes the problem.

Good luck!

**Comment by davidism** [comment]
Upgrade Flask-SQLAlchemy

**Comment by davidism** [comment]
Be sure to follow the template when opening an issue.

**Comment by cnicodeme** [comment]
@davidism Upgrading doesn't work.

With the latest version available : 

flask-sqlalchemy-2.5.1
sqlalchemy-1.4.4

I have the following exception:

```
Traceback (most recent call last):
  File "/home/user/www/project/api/env/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/user/www/project/api/env/lib/python3.8/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/home/user/www/project/api/env/lib/python3.8/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/user/www/project/api/env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/user/www/project/api/env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/user/www/project/api/env/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/user/www/project/api/env/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/user/www/project/api/env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/user/www/project/api/env/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/user/www/project/api/env/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/user/www/project/api/apps/credits/views.py", line 15, in plans
    plans_list = Plan.find_actives(request.headers.get('authorization', '')[7:] or None)
  File "/home/user/www/project/api/apps/credits/models.py", line 35, in find_actives
    query = cls.query.filter(cls.removed == None)  # noqa
  File "/home/user/www/project/api/env/lib/python3.8/site-packages/flask_sqlalchemy/__init__.py", line 552, in __get__
    return type.query_class(mapper, session=self.sa.session())
  File "/home/user/www/project/api/env/lib/python3.8/site-packages/sqlalchemy/orm/scoping.py", line 129, in __call__
    return self.registry()
  File "/home/user/www/project/api/env/lib/python3.8/site-packages/sqlalchemy/util/_collections.py", line 1010, in __call__
    return self.registry.setdefault(key, self.createfunc())
  File "/home/user/www/project/api/env/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 4036, in __call__
    return self.class_(**local_kw)
  File "/home/user/www/project/api/env/lib/python3.8/site-packages/flask_sqlalchemy/__init__.py", line 176, in __init__
    bind = options.pop('bind', None) or db.engine
  File "/home/user/www/project/api/env/lib/python3.8/site-packages/flask_sqlalchemy/__init__.py", line 998, in engine
    return self.get_engine()
  File "/home/user/www/project/api/env/lib/python3.8/site-packages/flask_sqlalchemy/__init__.py", line 1017, in get_engine
    return connector.get_engine()
  File "/home/user/www/project/api/env/lib/python3.8/site-packages/flask_sqlalchemy/__init__.py", line 593, in get_engine
    sa_url, options = self.get_options(sa_url, echo)
  File "/home/user/www/project/api/env/lib/python3.8/site-packages/flask_sqlalchemy/__init__.py", line 608, in get_options
    sa_url, options = self._sa.apply_driver_hacks(self._app, sa_url, options)
  File "/home/user/www/project/api/env/lib/python3.8/site-packages/flask_sqlalchemy/__init__.py", line 937, in apply_driver_hacks
    options.setdefault('pool_size', 10)
AttributeError: 'NoneType' object has no attribute 'setdefault'
```
