### ISSUE TITLE
SQLALCHEMY_ENGINE_OPTIONS is optional but the latest release seems to expect it

### ISSUE THREAD

**Issue by hosseinsh** [pallets/flask-sqlalchemy#948]
```
Traceback (most recent call last):
  File "/home/travis/build/Netflix/lemur/lemur/tests/conftest.py", line 79, in db
    _db.drop_all()
  File "/home/travis/virtualenv/python3.7.6/lib/python3.7/site-packages/flask_sqlalchemy/__init__.py", line 1102, in drop_all
    self._execute_for_all_tables(app, bind, 'drop_all')
  File "/home/travis/virtualenv/python3.7.6/lib/python3.7/site-packages/flask_sqlalchemy/__init__.py", line 1086, in _execute_for_all_tables
    op(bind=self.get_engine(app, bind), **extra)
  File "/home/travis/virtualenv/python3.7.6/lib/python3.7/site-packages/flask_sqlalchemy/__init__.py", line 1017, in get_engine
    return connector.get_engine()
  File "/home/travis/virtualenv/python3.7.6/lib/python3.7/site-packages/flask_sqlalchemy/__init__.py", line 593, in get_engine
    sa_url, options = self.get_options(sa_url, echo)
  File "/home/travis/virtualenv/python3.7.6/lib/python3.7/site-packages/flask_sqlalchemy/__init__.py", line 615, in get_options
    options.update(self._app.config['SQLALCHEMY_ENGINE_OPTIONS'])
AttributeError: 'NoneType' object has no attribute 'update'
```

While updating updatiing flask-sqlalchemy from 2.4.4 to 2.5, we run to the above issue.

SQLALCHEMY_ENGINE_OPTIONS is an optional config parameter, and flask_sqlalchemy should be able to handle if it is not being defined. 

Environment:

- Python version:  Python: 3.7
- Flask-SQLAlchemy version: 2.5.1
- SQLAlchemy version: 1.3.16

**Comment by davidism** [comment]
I can't reproduce this issue. When the extension is registered with the app, it sets all available config keys to default values. https://github.com/pallets/flask-sqlalchemy/blob/da0e0df80cc368d95dc5a118ce857cead172aded/flask_sqlalchemy/__init__.py#L869

Additionally, the error you've shown is not about that config option being `None`, it's about the local `options` variable in `get_options` being `None`. Note that the signature for `apply_pool_defaults` and `apply_driver_hacks` changed in 2.5, so if you're overriding them you need to update `apply_pool_defaults` to return `options`, and `apply_driver_hacks` to return `sa_url, options`.

**Comment by hosseinsh** [comment]
overwriting appeared to be the culprit. 
`apply_pool_defaults()` was set, inspired by this workaround: 
https://github.com/pallets/flask-sqlalchemy/issues/589#issuecomment-361075700

thanks for looking into this @davidism

**Comment by davidism** [comment]
I updated those comments to reflect Flask-SQLAlchemy 2.5.

**Comment by hosseinsh** [comment]
Excellent idea, thank you.
